### PR TITLE
Version: 1.25

### PR DESCRIPTION
**Pull request by Sharlikran**
- Formatting
- Replaced FTC.Player:GetClass() with ZOS API
- Updated Powertype flags to CombatMechanicFlags
- Nit Picks such as leaking vars
- Improved LAM menu color picker handling

### CODE REVIEW

**Comment by Sharlikran** [comment]
Sorry about the commit noise. I just have too many things set to auto remove trailing spaces and indent to 2 spaces rather then 4. I rebased it a little to reduce things but it's hard to eliminate all of it.

**Comment by Rhyono** [comment]
The less whitespace the better. I'll get this out now. Thanks!

**Comment by Sharlikran** [comment]
@Rhyono Thanks for uploading that because the old constants (`POWERTYPE_HEALTH`, `POWERTYPE_MAGICKA`, `POWERTYPE_STAMINA` and others) are no longer used. I have not found everything yet that needs to be updated.

However, so far I can't find anyone who can answer my main concern.

What does this mod do that is unique to each specific class. Like notifications. I want to add anything needed for the new Arcanist class. When you have a certain amount of Crux or something. For example with a Sorcerer and Crystal Shards.

However, I'm new to the mod and when I ask other people about the features and what might be a good thing to add everyone just keeps telling me that they have Lua errors or it doesn't work with an Arcanist. It will work with an Arcanist now but I'm not getting any clarification of features.

Also BuffIds and AbilityIds may have changed so I have to double check all of that.

For this file: `FoundryTacticalCombat\buffs\effects.lua` I need to add anything new. However, I'm not sure what all qualifies to be in that file. Are all the buffs and debuffs in that file?

**Comment by Rhyono** [comment]
I didn't handle that part of the addon, but it separated out shields and taunts, then universal things like boons and vampirism were given specific identifiers. There is a built in ignored list, but anything outside of that should be automatically picked up. I would assume there are a few that need to be classified in that file for Arcanist, but without classifying them, they may still display, just differently.

**Comment by Sharlikran** [comment]
Do you have contact with anyone that could help explain any of that? If not no worries I'm just going to check ZOS functions and events for changes. Then abilities and skills to see if their IDs changed.

**Comment by Rhyono** [comment]
I don't, but the easiest way would be to get an Arcanist to use those abilities and have it spit out the ids so you can add them to each of those groups. I don't believe you'll need to change the code, only add the new ids. Hopefully the other ids didn't change, as they usually don't between updates.

**Comment by Sharlikran** [comment]
I have found some. In fact while the Id didn't change the name has changed to Carterize. That changed in update 10. So I'm going through them all to be sure. Also one of the ability ids used to return something and now it doesn't, returns nil. So I have no idea what it was. It was to mark something as an area effect. There is Ground and Cone, do you know what the third type might have been?

**Comment by Sharlikran** [comment]
https://github.com/Rhyono/Foundry-Tactical-Combat/blob/fdc95b016f8a45382c79f8bb0f1430ea59b7c738/buffs/functions.lua#L155

22784 is no longer valid so it won't achieve what it did in the past. The number is arbitrary what isn't arbitrary is that the ability returns a description which is used as a type. As I mentioned Ground or Cone, so the third one simply has to return the type that whatever 22784 used to be.

**Comment by Sharlikran** [comment]
Same with this, `GetAbilityName(15356)` no longer exists. It was used for sprinting and crouching. However, for crouch it is Crouch Drain.

**Comment by Sharlikran** [comment]
https://en.uesp.net/wiki/Online:Bracing

https://github.com/Rhyono/Foundry-Tactical-Combat/blob/fdc95b016f8a45382c79f8bb0f1430ea59b7c738/buffs/effects.lua#L35

Bracing as a toggle was removed in update 10 and replaced with Wrath, then replaced in 16 with Revitalize

**Comment by Rhyono** [comment]
Ah, I wasn't aware of that. I don't know what the third type would be. Looking at this, I don't know if anything can be derived from it that lends a clue: https://en.uesp.net/wiki/Online:Area_of_Effect

**Comment by Sharlikran** [comment]
@Rhyono I just chose to use the API that returns the type of effect, which is an area effect. Using that or the old boolean was the same most of the time. So it's probably going to catch the missing or unknown boolean. It can be reverted if anyone can explain the older code.

**Pull request merged**
